# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7e22c55ee5723b0dbec1b222458b797f97eb239bc9f69abc8055e76f01428941447758bc5b8017cbc70a7ccf87ce8f7948a11e9dacbc8208287cf024118607e

test:
  secret_key_base: 3ae96a63b7e04fd4698b7b95685a6124f480fd682716a1ec82a51a317d2685f095c0760a0e37b2953fcad6a6fad80ff8ab4513caa2c1ee3c8c3a75db677804ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
