# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5a1382b7273f11b07525400a39caeecac20c0365d096e776c90660fa13573322bce764f73bc40344ec8fd157f15365f89a01de532e6374f3743431109aa6b6d

test:
  secret_key_base: 4b895dc5841c7d7e48ca4db5415c34ac5037490c7af70b5298b3a024494a9f0c96ec33cc607c7d6afe897cb1365310f0dec4483cf54c229270b2ad763f595fe7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
